# Generated by Django 6.0.3 on 2026-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0003_order_shipping_fee_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Paid Online'), ('POD', 'Pay on Delivery')], default='Online', max_length=10),
        ),
    ]
