# Generated by Django 6.0.3 on 2026-04-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0005_courierprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierprofile',
            name='chosen_halls',
        ),
        migrations.RemoveField(
            model_name='courierprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='locations',
            field=models.JSONField(default=list),
        ),
    ]
