# Generated by Django 6.0.3 on 2026-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0006_remove_courierprofile_chosen_halls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierprofile',
            name='locations',
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='location_1',
            field=models.CharField(choices=[('John', 'John Hall'), ('Paul', 'Paul Hall'), ('Mary', 'Mary Hall'), ('Lydia', 'Lydia Hall')], default='John Hall', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='location_2',
            field=models.CharField(blank=True, choices=[('John', 'John Hall'), ('Paul', 'Paul Hall'), ('Mary', 'Mary Hall'), ('Lydia', 'Lydia Hall')], max_length=50, null=True),
        ),
    ]
