# Generated by Django 6.0.3 on 2026-04-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0007_remove_courierprofile_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierprofile',
            name='location_1',
            field=models.CharField(choices=[('John Hall', 'John Hall'), ('Paul Hall', 'Paul Hall'), ('Mary Hall', 'Mary Hall'), ('Lydia Hall', 'Lydia Hall')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courierprofile',
            name='location_2',
            field=models.CharField(blank=True, choices=[('John Hall', 'John Hall'), ('Paul Hall', 'Paul Hall'), ('Mary Hall', 'Mary Hall'), ('Lydia Hall', 'Lydia Hall')], max_length=50, null=True),
        ),
    ]
