# Generated by Django 6.0.3 on 2026-05-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0010_order_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packing', 'Packing'), ('Transit', 'Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Timeout', 'Timeout')], default='Accepted', max_length=20),
        ),
    ]
