# Generated by Django 6.0.3 on 2026-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Order Accepted'), ('Packing', 'Packing Order'), ('Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Timeout', 'Timeout')], default='Accepted', max_length=20),
        ),
    ]
