# Generated by Django 6.0.3 on 2026-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Courier', 'Courier')], max_length=10, null=True),
        ),
    ]
