# Generated by Django 6.0.3 on 2026-05-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0014_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready for Pickup'), ('Accepted', 'Order Accepted'), ('Packing', 'Packing Order'), ('Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Timeout', 'Timeout')], default='Accepted', max_length=20),
        ),
    ]
