# Generated by Django 6.0.3 on 2026-08-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0019_courierprofile_is_deleted_alter_courierprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Pack', 'Pack'), ('Carton', 'Carton')], default='Piece', max_length=20),
        ),
    ]
