# Generated by Django 6.0.3 on 2026-08-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groocy', '0020_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_type',
            field=models.CharField(choices=[('piece', 'Piece'), ('pack', 'Pack'), ('carton', 'Carton')], default='piece', max_length=10),
        ),
    ]
